// invitados.js
export const invitados = {
  '1': { nombre: 'Manuel Jerez', adultos: 4, ninos: 0 },
  '2': { nombre: 'Manuel Jerez', adultos: 2, ninos: 0 },
  '3': { nombre: 'Edson Jerez', adultos: 2, ninos: 2 },
  '4': { nombre: 'Khrista Jerez', adultos: 2, ninos: 0 },
  '5': { nombre: 'Joshua Jerez', adultos: 2, ninos: 0 },
  '6': { nombre: 'Winston Jerez', adultos: 1, ninos: 0 },
  '7': { nombre: 'Gustavo Alvarado', adultos: 1, ninos: 0 },
  '8': { nombre: 'Jessica Alvarado', adultos: 2, ninos: 0 },
  '9': { nombre: 'Byron Garcia', adultos: 1, ninos: 0 },
  '10': { nombre: 'Jorge Mario Garcia', adultos: 2, ninos: 0 },
  '11': { nombre: 'Emilio Arias', adultos: 4, ninos: 1 },
  '12': { nombre: 'Pamela Roldán', adultos: 2, ninos: 3 },
  '13': { nombre: 'Rosa Roldán Velasquez', adultos: 1, ninos: 1 },
  '14': { nombre: 'Eduardo Toledo', adultos: 1, ninos: 0 },
  '15': { nombre: 'Liz Velasquez', adultos: 1, ninos: 0 },
  '16': { nombre: 'Rosa Roldán', adultos: 4, ninos: 0 },
  '17': { nombre: 'Mario Mendez', adultos: 2, ninos: 0 },
  '18': { nombre: 'Maria Fernanda Mendez', adultos: 2, ninos: 0 },
  '19': { nombre: 'Valeria Mendez', adultos: 2, ninos: 0 },
  '20': { nombre: 'Melanie Mendez', adultos: 1, ninos: 0 },
  '21': { nombre: 'Regina de Roldán', adultos: 2, ninos: 0 },
  '22': { nombre: 'Luis Roldán', adultos: 2, ninos: 1 },
  '23': { nombre: 'Darline Roldán', adultos: 1, ninos: 2 },
  '24': { nombre: 'Jorge Jerez', adultos: 2, ninos: 3 },
  '25': { nombre: 'Fran Solorzano', adultos: 1, ninos: 0 },
  '26': { nombre: 'Josue Roldán', adultos: 2, ninos: 0 },
  '27': { nombre: 'Eddie Roldán', adultos: 2, ninos: 0 },
  '28': { nombre: 'Jorge Garcia', adultos: 2, ninos: 0 },
  '29': { nombre: 'Miguel Garcia', adultos: 1, ninos: 0 },
  '30': { nombre: 'Camila Lopez', adultos: 2, ninos: 0 },
  '31': { nombre: 'Mario Pinzon', adultos: 1, ninos: 0 },
  '32': { nombre: 'Jose Santiago Gonzalez', adultos: 1, ninos: 0 },
  '33': { nombre: 'Nicoll Hernandez', adultos: 1, ninos: 0 },
  '34': { nombre: 'Mia Vargas', adultos: 1, ninos: 0 },
  '35': { nombre: 'Alvaro Longo', adultos: 1, ninos: 0 },
  '36': { nombre: 'Santiago Mazariegos', adultos: 1, ninos: 0 },
  '37': { nombre: 'Jose Rodrigo Mazariegos', adultos: 1, ninos: 0 },
  '38': { nombre: 'Mathias Garcia', adultos: 1, ninos: 0 },
  '39': { nombre: 'Elisa Rivas', adultos: 1, ninos: 0 },
  '40': { nombre: 'Sofia Lopez', adultos: 1, ninos: 0 },
  '41': { nombre: 'Andrea Gonzalez', adultos: 1, ninos: 0 },
  '42': { nombre: 'Malu Flores', adultos: 1, ninos: 0 },
  '43': { nombre: 'Isa Palma', adultos: 1, ninos: 0 },
  '44': { nombre: 'Allison Reyes', adultos: 1, ninos: 0 },
  '45': { nombre: 'Danna Regina Muralles', adultos: 1, ninos: 0 },
  '46': { nombre: 'Sofia Sian', adultos: 1, ninos: 0 },
  '47': { nombre: 'Daniela Jiménez', adultos: 1, ninos: 0 },
  '48': { nombre: 'Natalia Paiz', adultos: 1, ninos: 0 },
  '49': { nombre: 'Isabell Ochoa', adultos: 1, ninos: 0 },
  '50': { nombre: 'Alanis Medina', adultos: 1, ninos: 0 },
  '51': { nombre: 'Faustino Iraheta', adultos: 1, ninos: 0 },
  '52': { nombre: 'Pablo Tale', adultos: 1, ninos: 0 },
  '53': { nombre: 'Manuel Uribio', adultos: 1, ninos: 0 },
  '54': { nombre: 'Santiago Cuevas', adultos: 1, ninos: 0 },
  '55': { nombre: 'Rodrigo Rojas', adultos: 1, ninos: 0 },
  '56': { nombre: 'Estaban Toralla', adultos: 1, ninos: 0 },
  '57': { nombre: 'Luciana', adultos: 1, ninos: 0 },
  '58': { nombre: 'Sacarlett Culajay', adultos: 1, ninos: 0 },
  '59': { nombre: 'Paula Culajay', adultos: 1, ninos: 0 },
  '60': { nombre: 'Isa Garcia', adultos: 1, ninos: 0 },
  '61': { nombre: 'Krista Lorenzo', adultos: 1, ninos: 0 },
  '62': { nombre: 'Gaby Guzman', adultos: 1, ninos: 0 },
  '63': { nombre: 'Miriam Corado', adultos: 1, ninos: 0 },
  '64': { nombre: 'Leroy Gillespie', adultos: 1, ninos: 0 },
  '65': { nombre: 'Adriana Lemus', adultos: 1, ninos: 0 },
  '66': { nombre: 'Juan Carlos Lemus', adultos: 1, ninos: 0 },
  '67': { nombre: 'Jimena Morales', adultos: 1, ninos: 0 },
  '68': { nombre: 'Daniela Melendez', adultos: 1, ninos: 0 },
  '69': { nombre: 'Jerson Alas', adultos: 1, ninos: 0 },
  '70': { nombre: 'Eddie Roldán', adultos: 2, ninos: 0 },
  '71': { nombre: 'Rene Venegas', adultos: 2, ninos: 0 },
  '72': { nombre: 'Denis Pinto', adultos: 2, ninos: 0 },
  '73': { nombre: 'Samuel Castellanos', adultos: 2, ninos: 0 },
  '74': { nombre: 'Martin Rivera', adultos: 1, ninos: 0 },
  '75': { nombre: 'Aron Guevara', adultos: 1, ninos: 0 },
};

  
